language: java
sudo: required
jdk:
  - openjdk8
cache:
  directories:
  - $HOME/.CommandBox
env:
  matrix:
    - ENGINE=lucee@5
    - ENGINE=adobe@2018
    - ENGINE=adobe@2016
before_install:
  - curl -fsSl https://downloads.ortussolutions.com/debs/gpg | sudo apt-key add -
  - sudo echo "deb http://downloads.ortussolutions.com/debs/noarch /" | sudo tee -a /etc/apt/sources.list.d/commandbox.list
install:
  - sudo apt-get update && sudo apt-get --assume-yes install commandbox
  - box install
before_script:
  - box server start cfengine=$ENGINE port=8500
script:
  - box testbox run runner='http://127.0.0.1:8500/tests/runner.cfm'
notifications:
  email: false
